### ISSUE TITLE
Need Better Error Handling for Results that are Missing Certain Fields

### ISSUE THREAD

**Issue by josh-spratt** [josh-spratt/drug-lookup#5]
For example:
`Traceback (most recent call last):
  File "main-v0.py", line 116, in <module>
    parse_desired_drug_data_from_json_response(dict_of_specific_drug_result)
  File "main-v0.py", line 89, in parse_desired_drug_data_from_json_response
    primary_site = resultant_dict['primary_site']
KeyError: 'primary_site'`
- the drug of interest does not have a 'primary_site' field listed
- will need a way to handle missing fields maybe try/except block, or .get("primary_site") for each field

**Comment by josh-spratt** [comment]
have resolved by writing a nested function which checks for the key in the resultant dict
def check_dict_for_key(dict, key):
        if key in dict.keys():
            print(key)
            print(dict[key])
        else:
            print(f"{key} not found")
